Resources:
  RemotePatientMonitoringCenterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.DBPrefix}CenterTable-${self:provider.stage}
      KeySchema:
        - AttributeName: centerId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: centerId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
  RemotePatientMonitoringNurseTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.DBPrefix}NurseTable-${self:provider.stage}
      KeySchema:
        - AttributeName: nurseId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: nurseId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
  RemotePatientMonitoringPatientTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.DBPrefix}PatientTable-${self:provider.stage}
      KeySchema:
        - AttributeName: patientId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: patientId
          AttributeType: S
        - AttributeName: phone
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: RemotePatientMonitoringPatientTableGSIPhone
          KeySchema:
            - AttributeName: phone
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
  RemotePatientMonitoringTempLoginTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:provider.environment.DBPrefix}TempLoginTable-${self:provider.stage}
      KeySchema:
        - AttributeName: phone
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: phone
          AttributeType: S
        - AttributeName: loginKey
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: RemotePatientMonitoringTempLoginTableGSIToken
          KeySchema:
            - AttributeName: loginKey
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
