name: github pages

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: npm install
        run: |
          cp config/stg.json.sample config/stg.json # for ignoring install error
          cp config/stg.json.sample config/prd.json # for ignoring install error
          npm install

      - name: build swagger yaml
        run: npm run build:swagger-yaml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/gh-swagger-ui
